In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [12]:
propose = pd.read_csv('result/kc/propose_Rank_table_kc_network.csv')
all_in = pd.concat([propose], axis=1, sort=False)

Top_Five_all_in = pd.DataFrame(all_in.loc[0:2])
ranking_table_all_in = pd.concat([Top_Five_all_in['nodes'],Top_Five_all_in['nodes_tr'], Top_Five_all_in['nodes_bc'], 
                                  Top_Five_all_in['nodes_cnc'],
                                  Top_Five_all_in['nodes_dc'], Top_Five_all_in['nodes_ec'],Top_Five_all_in['nodes_pr'],
                                  Top_Five_all_in['nodes_TC'], 
                                  Top_Five_all_in['nodes_PI'], Top_Five_all_in['nodes_CC'],Top_Five_all_in['nodes_TPN']], 
                                 axis=1, sort=False)
#float_col = ranking_table_all_in.select_dtypes(include = ['float64']) # This will select float columns only
# list(float_col.columns.values)
#for col in float_col.columns.values:
#    ranking_table_all_in[col] = ranking_table_all_in[col].astype('int64')
#ranking_table_all_in.to_csv('result/usair/ranking_table_all_in_usair_network.csv')

In [13]:
ranking_table_all_in

,nodes,nodes_tr,nodes_bc,nodes_cnc,nodes_dc,nodes_ec,nodes_pr,nodes_TC,nodes_PI,nodes_CC,nodes_TPN
0,1,1,1,1,34,34,34,1,1,1,1.0
1,34,34,34,3,1,1,1,34,34,34,34.0
2,33,33,33,34,33,3,33,33,33,3,33.0

In [14]:
# calculate the kendall's correlation between two variables# calcul 
from numpy.random import rand
from numpy.random import seed
from scipy.stats import kendalltau

# prepare data
data1 = ranking_table_all_in['nodes']
data2 = data1+ ranking_table_all_in['nodes_TPN']
# calculate kendall's correlation
coef, p = kendalltau(data1, data2)
print('Kendall correlation coefficient: %.3f' % coef)
# interpret the significance
alpha = 0.05
if p > alpha:
	print('Samples are uncorrelated (fail to reject H0) p=%.3f' % p)
else:
	print('Samples are correlated (reject H0) p=%.3f' % p)

Kendall correlation coefficient: 1.000
Samples are uncorrelated (fail to reject H0) p=0.117

In [15]:
# Importing required libraries
import researchpy as rp
from scipy import stats
#The casewise method returns all information in 3 dataframes
#corr_type, corr_matrix, corr_ps=>
corr_type, corr_matrix, corr_ps = rp.corr_case(ranking_table_all_in[['nodes','nodes_tr', 'nodes_bc', 'nodes_cnc', 'nodes_dc', 'nodes_ec','nodes_pr','nodes_TC', 'nodes_PI', 'nodes_CC','nodes_TPN']])
#PAIRWISEcorrelation
corr_pair = rp.corr_pair(ranking_table_all_in[['nodes','nodes_TC', 'nodes_PI', 'nodes_CC','nodes_TPN']])

In [23]:
corr_matrix
#corr_matrix.to_csv('result/kc/corr_matrix_kcnew.csv')

,nodes,nodes_tr,nodes_bc,nodes_cnc,nodes_dc,nodes_ec,nodes_pr,nodes_TC,nodes_PI,nodes_CC,nodes_TPN
nodes,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1
nodes_tr,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1
nodes_bc,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1
nodes_cnc,0.5236,0.5236,0.5236,1,0.4285,-0.5,0.4285,0.5236,0.5236,-0.4036,0.5236
nodes_dc,-0.5454,-0.5454,-0.5454,0.4285,1,0.5682,1,-0.5454,-0.5454,-0.9996,-0.5454
nodes_ec,-0.9996,-0.9996,-0.9996,-0.5,0.5682,1,0.5682,-0.9996,-0.9996,-0.5906,-0.9996
nodes_pr,-0.5454,-0.5454,-0.5454,0.4285,1,0.5682,1,-0.5454,-0.5454,-0.9996,-0.5454
nodes_TC,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1
nodes_PI,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1
nodes_CC,0.5682,0.5682,0.5682,-0.4036,-0.9996,-0.5906,-0.9996,0.5682,0.5682,1,0.5682
nodes_TPN,1,1,1,0.5236,-0.5454,-0.9996,-0.5454,1,1,0.5682,1

In [21]:
import scipy.stats as stats
data1 = ranking_table_all_in['nodes']
data2 = ranking_table_all_in['nodes_TPN']
tau, p_value = stats.kendalltau(data1, data2)
tau,p_value

(1.0, 0.1171850871981381)

In [22]:
import scipy.stats
scipy.stats.spearmanr(data1,data2)

SpearmanrResult(correlation=1.0, pvalue=0.0)

In [19]:
kd=ranking_table_all_in.corr(method ='kendall')
#kd.to_csv('result/kc/kdcorr_matrix_kc.csv')
kd

,nodes,nodes_tr,nodes_bc,nodes_cnc,nodes_dc,nodes_ec,nodes_pr,nodes_TC,nodes_PI,nodes_CC,nodes_TPN
nodes,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_tr,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_bc,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_cnc,0.333333,0.333333,0.333333,1.000000,-0.333333,-0.333333,-0.333333,0.333333,0.333333,0.333333,0.333333
nodes_dc,-1.000000,-1.000000,-1.000000,-0.333333,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000
nodes_ec,-1.000000,-1.000000,-1.000000,-0.333333,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000
nodes_pr,-1.000000,-1.000000,-1.000000,-0.333333,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000
nodes_TC,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_PI,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_CC,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000
nodes_TPN,1.000000,1.000000,1.000000,0.333333,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000