In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [6]:
propose = pd.read_csv('result/usair/ranking_table_usair.csv')
all_in = pd.concat([propose], axis=1, sort=False)

Top_Five_all_in = pd.DataFrame(all_in.loc[0:2])
ranking_table_all_in = pd.concat([Top_Five_all_in['NDR'],Top_Five_all_in['TR'], Top_Five_all_in['BC'], Top_Five_all_in['CNC'],
                                  Top_Five_all_in['DC'], Top_Five_all_in['EC'],Top_Five_all_in['PR'],
                                  Top_Five_all_in['TC'], 
                                  Top_Five_all_in['PI'], Top_Five_all_in['CC'],Top_Five_all_in['TPN']], 
                                 axis=1, sort=False)
#float_col = ranking_table_all_in.select_dtypes(include = ['float64']) # This will select float columns only
# list(float_col.columns.values)
#for col in float_col.columns.values:
#    ranking_table_all_in[col] = ranking_table_all_in[col].astype('int64')
#ranking_table_all_in.to_csv('result/usair/ranking_table_all_in_usair_network.csv')
#ranking_table_all_in

   NDR   TR   BC  CNC   DC   EC   PR   TC   PI  CC  TPN
0    1    1    1    1    1    1   47    1    1   1    1
1   47   47  206   47   47   47    1   47   47  47   47
2  110  110   47   55  110  110  206  110  110   4  110

In [7]:
# calculate the kendall's correlation between variables
kd=ranking_table_all_in.corr(method ='kendall')
#kd.to_csv('result/usair/correlation/kdcorr_matrix_usair.csv')
kd

,NDR,TR,BC,CNC,DC,EC,PR,TC,PI,CC,TPN
NDR,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
TR,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
BC,0.333333,0.333333,1.000000,0.333333,0.333333,0.333333,-0.333333,0.333333,0.333333,1.000000,0.333333
CNC,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
DC,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
EC,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
PR,0.333333,0.333333,-0.333333,0.333333,0.333333,0.333333,1.000000,0.333333,0.333333,-0.333333,0.333333
TC,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
PI,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000
CC,0.333333,0.333333,1.000000,0.333333,0.333333,0.333333,-0.333333,0.333333,0.333333,1.000000,0.333333
TPN,1.000000,1.000000,0.333333,1.000000,1.000000,1.000000,0.333333,1.000000,1.000000,0.333333,1.000000

In [9]:
# calculate the pearson's correlation between variables 
ps=ranking_table_all_in.corr(method ='pearson')
#ps.to_csv('result/usair/correlation/pscorr_matrix_usair.csv')
ps

,NDR,TR,BC,CNC,DC,EC,PR,TC,PI,CC,TPN
NDR,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
TR,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
BC,0.125353,0.125353,1.000000,0.565796,0.125353,0.125353,-0.500000,0.125353,0.125353,0.987674,0.125353
CNC,0.888966,0.888966,0.565796,1.000000,0.888966,0.888966,0.431179,0.888966,0.888966,0.429762,0.888966
DC,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
EC,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
PR,0.796518,0.796518,-0.500000,0.431179,0.796518,0.796518,1.000000,0.796518,0.796518,-0.629390,0.796518
TC,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
PI,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000
CC,-0.031481,-0.031481,0.987674,0.429762,-0.031481,-0.031481,-0.629390,-0.031481,-0.031481,1.000000,-0.031481
TPN,1.000000,1.000000,0.125353,0.888966,1.000000,1.000000,0.796518,1.000000,1.000000,-0.031481,1.000000

In [5]:
#import scipy.stats
#scipy.stats.spearmanr(data1,data2)