In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [9]:
propose = pd.read_csv('result/kc--/ranking_table_kc.csv')
all_in = pd.concat([propose], axis=1, sort=False)

Top_Five_all_in = pd.DataFrame(all_in.loc[0:3])
ranking_table_all_in = pd.concat([Top_Five_all_in['NDR'],Top_Five_all_in['TR'], Top_Five_all_in['BC'], Top_Five_all_in['CNC'],
                                  Top_Five_all_in['DC'], Top_Five_all_in['EC'],Top_Five_all_in['PR'],
                                  Top_Five_all_in['TC'], 
                                  Top_Five_all_in['PI'], Top_Five_all_in['CC'],Top_Five_all_in['TPN']], 
                                 axis=1, sort=False)
#float_col = ranking_table_all_in.select_dtypes(include = ['float64']) # This will select float columns only
# list(float_col.columns.values)
#for col in float_col.columns.values:
#    ranking_table_all_in[col] = ranking_table_all_in[col].astype('int64')
#ranking_table_all_in.to_csv('result/usair/ranking_table_all_in_usair_network.csv')
ranking_table_all_in

   NDR  TR  BC  CNC  DC  EC  PR  TC  PI  CC   TPN
0    0   0   0    0  33  33  33   0   0   0   0.0
1   33  33  33    2   0   0   0  33  33  33  33.0
2   32  32  32   33  32   2  32  32  32   2  32.0
3    1   1   2   31   2  32   1   1   1  31   2.0

In [10]:
# calculate the kendall's correlation between variables
kd=ranking_table_all_in.corr(method ='kendall')
#kd.to_csv('result/dolphins--/correlation/kdcorr_matrix_dolphins.csv')
kd

,NDR,TR,BC,CNC,DC,EC,PR,TC,PI,CC,TPN
NDR,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000
TR,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000
BC,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000
CNC,0.333333,0.333333,0.333333,1.000000,0.000000,-0.333333,0.000000,0.333333,0.333333,0.000000,0.333333
DC,-0.666667,-0.666667,-0.666667,0.000000,1.000000,0.666667,1.000000,-0.666667,-0.666667,-1.000000,-0.666667
EC,-1.000000,-1.000000,-1.000000,-0.333333,0.666667,1.000000,0.666667,-1.000000,-1.000000,-0.666667,-1.000000
PR,-0.666667,-0.666667,-0.666667,0.000000,1.000000,0.666667,1.000000,-0.666667,-0.666667,-1.000000,-0.666667
TC,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000
PI,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000
CC,0.666667,0.666667,0.666667,0.000000,-1.000000,-0.666667,-1.000000,0.666667,0.666667,1.000000,0.666667
TPN,1.000000,1.000000,1.000000,0.333333,-0.666667,-1.000000,-0.666667,1.000000,1.000000,0.666667,1.000000

In [11]:
# calculate the pearson's correlation between variables 
ps=ranking_table_all_in.corr(method ='pearson')
#ps.to_csv('result/usair/correlation/pscorr_matrix_usair.csv')
ps

,NDR,TR,BC,CNC,DC,EC,PR,TC,PI,CC,TPN
NDR,1.000000,1.000000,0.999741,0.064351,-0.078731,-0.999741,-0.062439,1.000000,1.000000,0.095521,0.999741
TR,1.000000,1.000000,0.999741,0.064351,-0.078731,-0.999741,-0.062439,1.000000,1.000000,0.095521,0.999741
BC,0.999741,0.999741,1.000000,0.080121,-0.094747,-0.999497,-0.078731,0.999741,0.999741,0.111762,1.000000
CNC,0.064351,0.064351,0.080121,1.000000,0.012758,-0.048481,-0.002011,0.064351,0.064351,0.004145,0.080121
DC,-0.078731,-0.078731,-0.094747,0.012758,1.000000,0.095250,0.999741,-0.078731,-0.078731,-0.999732,-0.094747
EC,-0.999741,-0.999741,-0.999497,-0.048481,0.095250,1.000000,0.078731,-0.999741,-0.999741,-0.111762,-0.999497
PR,-0.062439,-0.062439,-0.078731,-0.002011,0.999741,0.078731,1.000000,-0.062439,-0.062439,-0.999449,-0.078731
TC,1.000000,1.000000,0.999741,0.064351,-0.078731,-0.999741,-0.062439,1.000000,1.000000,0.095521,0.999741
PI,1.000000,1.000000,0.999741,0.064351,-0.078731,-0.999741,-0.062439,1.000000,1.000000,0.095521,0.999741
CC,0.095521,0.095521,0.111762,0.004145,-0.999732,-0.111762,-0.999449,0.095521,0.095521,1.000000,0.111762
TPN,0.999741,0.999741,1.000000,0.080121,-0.094747,-0.999497,-0.078731,0.999741,0.999741,0.111762,1.000000

In [5]:
#import scipy.stats
#scipy.stats.spearmanr(data1,data2)