In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
propose = pd.read_csv('result/usair/propose_Rank_table_usair_network.csv')
all_in = pd.concat([propose], axis=1, sort=False)

Top_Five_all_in = pd.DataFrame(all_in.loc[0:2])
ranking_table_all_in = pd.concat([Top_Five_all_in['nodes'],Top_Five_all_in['nodes_tr'], Top_Five_all_in['nodes_bc'], 
                                  Top_Five_all_in['nodes_cnc'],
                                  Top_Five_all_in['nodes_dc'], Top_Five_all_in['nodes_ec'],Top_Five_all_in['nodes_pr'],
                                  Top_Five_all_in['nodes_TC'], 
                                  Top_Five_all_in['nodes_PI'], Top_Five_all_in['nodes_CC'],Top_Five_all_in['nodes_TPN']], 
                                 axis=1, sort=False)
#float_col = ranking_table_all_in.select_dtypes(include = ['float64']) # This will select float columns only
# list(float_col.columns.values)
#for col in float_col.columns.values:
#    ranking_table_all_in[col] = ranking_table_all_in[col].astype('int64')
#ranking_table_all_in.to_csv('result/usair/ranking_table_all_in_usair_network.csv')

In [3]:
ranking_table_all_in

,nodes,nodes_tr,nodes_bc,nodes_cnc,nodes_dc,nodes_ec,nodes_pr,nodes_TC,nodes_PI,nodes_CC,nodes_TPN
0,1,1,1,1,1,1,47,1,1,1,1.0
1,47,47,206,47,47,47,1,47,47,47,47.0
2,110,110,47,55,110,110,206,110,110,4,110.0

In [8]:
# calculate the kendall's correlation between two variables# calcul 
from numpy.random import rand
from numpy.random import seed
from scipy.stats import kendalltau

# prepare data
data1 = ranking_table_all_in['nodes']
data2 = data1+ ranking_table_all_in['nodes_bc']
# calculate kendall's correlation
coef, p = kendalltau(data1, data2)
print('Kendall correlation coefficient: %.3f' % coef)
# interpret the significance
alpha = 0.05
if p > alpha:
	print('Samples are uncorrelated (fail to reject H0) p=%.3f' % p)
else:
	print('Samples are correlated (reject H0) p=%.3f' % p)

Kendall correlation coefficient: 0.333
Samples are uncorrelated (fail to reject H0) p=0.602

In [5]:
# Importing required libraries
import researchpy as rp
from scipy import stats
#The casewise method returns all information in 3 dataframes
#corr_type, corr_matrix, corr_ps=>
corr_type, corr_matrix, corr_ps = rp.corr_case(ranking_table_all_in[['nodes','nodes_tr', 'nodes_bc', 'nodes_cnc', 'nodes_dc', 'nodes_ec','nodes_pr','nodes_TC', 'nodes_PI', 'nodes_CC','nodes_TPN']])
#PAIRWISEcorrelation
corr_pair = rp.corr_pair(ranking_table_all_in[['nodes','nodes_TC', 'nodes_PI', 'nodes_CC','nodes_TPN']])

In [6]:
corr_matrix

,nodes,nodes_tr,nodes_bc,nodes_cnc,nodes_dc,nodes_ec,nodes_pr,nodes_TC,nodes_PI,nodes_CC,nodes_TPN
nodes,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_tr,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_bc,0.1254,0.1254,1,0.5658,0.1254,0.1254,-0.5,0.1254,0.1254,0.9877,0.1254
nodes_cnc,0.889,0.889,0.5658,1,0.889,0.889,0.4312,0.889,0.889,0.4298,0.889
nodes_dc,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_ec,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_pr,0.7965,0.7965,-0.5,0.4312,0.7965,0.7965,1,0.7965,0.7965,-0.6294,0.7965
nodes_TC,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_PI,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1
nodes_CC,-0.0315,-0.0315,0.9877,0.4298,-0.0315,-0.0315,-0.6294,-0.0315,-0.0315,1,-0.0315
nodes_TPN,1,1,0.1254,0.889,1,1,0.7965,1,1,-0.0315,1

In [7]:
import scipy.stats as stats
data1 = ranking_table_all_in['nodes']
data2 = ranking_table_all_in['nodes_TPN']
tau, p_value = stats.kendalltau(data1, data2)
tau,p_value

(1.0, 0.1171850871981381)